### ISSUE TITLE
Automatically pull images based on subject name/ID

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#89]
At the moment, our strongest lead for this feature is the JEMS system - the county-level jail booking software that officers use to view peoples' mugshots.

I talked with Toby on 4/18 about accessing the photos in JEMS, and he was unsure if there was a programmatic way to access the photos. He asked me to write up a description of what we wanted to do, so he can forward it to others who may know more.

As an alternative, he also mentioned that the Department of Licensing (DOL) has images of people, but made it sound impractical to connect to their legacy system.

The RMS system also carries photos, but they are generally associated with cases and not individuals.

**Comment by c-lliope** [comment]
This feature would require a large technical effort to integrate with another city-specific API. During the fellowship we decided it wasn't worth the effort, and we simply got CRT officers to upload people's images manually.

Closing because the leads we have to get this working aren't feasible. There may be a way to get this working in the future, but it probably requires discovering a better API to pull the images from.
